# for all available options see https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  concurrency: 2
  issues-exit-code: 0
  tests: false
  timeout: "5m"

output.format: "code-climate"

linters:
  enable:
    - "asasalint"
    - "asciicheck"
    - "bidichk"
    - "bodyclose"
    - "containedctx"
    - "contextcheck"
    - "cyclop"
    - "decorder"
    - "depguard"
    - "dogsled"
    - "dupword"
    - "durationcheck"
    - "errcheck"
    - "errchkjson"
    - "errname"
    - "errorlint"
    - "execinquery"
    - "exhaustive"
    - "exportloopref"
    - "forcetypeassert"
    - "funlen"
    - "gochecknoglobals"
    - "gochecknoinits"
    - "gocognit"
    - "goconst"
    - "gocritic"
    - "gocyclo"
    - "godot"
    - "godox"
    - "goerr113"
    - "gofmt"
    - "goheader"
    - "gomoddirectives"
    - "gomodguard"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "grouper"
    - "importas"
    - "ineffassign"
    - "interfacebloat"
    - "ireturn"
    - "loggercheck"
    - "maintidx"
    - "makezero"
    - "misspell"
    - "nakedret"
    - "nestif"
    - "nilerr"
    - "nilnil"
    - "noctx"
    - "nolintlint"
    - "nonamedreturns"
    - "nosprintfhostport"
    - "paralleltest"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "reassign"
    - "revive"
    - "staticcheck"
    - "stylecheck"
    - "tagliatelle"
    - "tenv"
    - "testableexamples"
    - "testpackage"
    - "thelper"
    - "tparallel"
    - "typecheck"
    - "unconvert"
    - "unparam"
    - "unused"
    - "usestdlibvars"
    - "varnamelen"
    - "whitespace"
    - "wrapcheck"
    - "wsl"
